/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.lang.reflect.Array;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testJson()  {

        Gson gson = new Gson();
        Reader reader = null;
        try {
            reader = Files.newBufferedReader(Paths.get("C:\\Users\\STUDENT\\Desktop\\401\\quotes\\app\\src\\test\\resources\\test.json"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        BufferedReader readJson = new BufferedReader(reader);

        Quote[] result = gson.fromJson(readJson, Quote[].class);


                        assertFalse(result.length == 0);
    }


}
